# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'

target 'FingerprintingDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FingerprintingDemo
  pod 'keyri-pod'

  target 'FingerprintingDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FingerprintingDemoUITests' do
    # Pods for testing
  end

end
